### ISSUE TITLE
Want to execute Bagel for pendigit dataset

### ISSUE THREAD

**Issue by dguhanus** [lizeyan/Bagel#1]
Hi Zeyan Li,
It is great to see your codes in Git Hub. I have downloaded them using git clone. I am very much interested in deep generative learning models. It looks like your work is one of the latest in RNN-VAE domain. I want to execute Bagel on pendigit dataset (http://odds.cs.stonybrook.edu/pendigits-dataset/) . Then I want to implement my own proposition on top of Bagle. 
I will cite your paper in my research paper. It will be a great help if you upload a python code to execute Bagle for any Univariate/Multivariate Timeseries dataset.

**Comment by lizeyan** [comment]
I am going to upload an executable code by Nov 11.

**Comment by dguhanus** [comment]
Hi Zeyan,
I think you have not yet uploaded a sample executable code. Please let me know if any progress happens.

**Comment by lizeyan** [comment]
I update a sample executable code and a sample data. May it helps you.
