### ISSUE TITLE
ValueError: dataset attribute should not be set after KpiFrameDataLoader is initialized

### ISSUE THREAD

**Issue by zn-coding** [lizeyan/Bagel#2]
Hi, author, there is an error after running main.py as shown in title, detail traceback as below:
Traceback (most recent call last):
  File "c:/Users/admin/Desktop/study/Bagel-master/main.py", line 22, in <module>
    model.fit(train_kpi.label_sampling(0.), valid_kpi)
  File "c:\Users\admin\Desktop\study\Bagel-master\model.py", line 132, in fit
    drop_last=True)
  File "c:\Users\admin\Desktop\study\Bagel-master\kpi_frame_dataloader.py", line 32, in __init__
    self.dataset = dataset
  File "C:\ProgramData\Anaconda3\envs\Bagel\lib\site-packages\torch\utils\data\dataloader.py", line 270, in __setattr__
    'initialized'.format(attr, self.__class__.__name__))
I can't solve it, so call for help,  thank u.

**Comment by WYXinna** [comment]
> Hi, author, there is an error after running main.py as shown in title, detail traceback as below:
> Traceback (most recent call last):
> File "c:/Users/admin/Desktop/study/Bagel-master/main.py", line 22, in 
> model.fit(train_kpi.label_sampling(0.), valid_kpi)
> File "c:\Users\admin\Desktop\study\Bagel-master\model.py", line 132, in fit
> drop_last=True)
> File "c:\Users\admin\Desktop\study\Bagel-master\kpi_frame_dataloader.py", line 32, in **init**
> self.dataset = dataset
> File "C:\ProgramData\Anaconda3\envs\Bagel\lib\site-packages\torch\utils\data\dataloader.py", line 270, in **setattr**
> 'initialized'.format(attr, self.**class**.**name**))
> I can't solve it, so call for help, thank u.

Hi,have you solved this question?

**Comment by zn-coding** [comment]
感谢回复，这个问题已经解决啦------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;WYXinna&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月28日(星期四) 晚上11:21
收件人:&nbsp;&quot;NetManAIOps/Bagel&quot;<Bagel@noreply.github.com&gt;;
抄送:&nbsp;&quot;zn-coding&quot;<mailfromzn@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NetManAIOps/Bagel] ValueError: dataset attribute should not be set after KpiFrameDataLoader is initialized (#2)

**Comment by WYXinna** [comment]
> 感谢回复，这个问题已经解决啦------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;WYXinna&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年5月28日(星期四) 晚上11:21 收件人:&nbsp;&quot;NetManAIOps/Bagel&quot;<Bagel@noreply.github.com&gt;; 抄送:&nbsp;&quot;zn-coding&quot;<mailfromzn@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [NetManAIOps/Bagel] ValueError: dataset attribute should not be set after KpiFrameDataLoader is initialized (#2)

求助😭请问你是怎么解决的呀

**Comment by lizeyan** [comment]
I think it may be caused by incompatibility of PyTorch.
When I wirte these codes, Pytorch is at about 0.4.
I do not remember the exact version, but I am sure I was not using 1.x.

Seems that the line `self.dataset = dataset` can be removed since it has already been initialized in the `__init__` of DataLoader

可以试试找个老版本的pytorch装一下，应该是1.x之前的版本。但是也可以自己改改代码，应该只是API不兼容了。反正我自己是不会去修这个bug了.....

**Comment by zn-coding** [comment]
哈哈哈，笑出了声，确实是pytorch版本的问题，换了一个就好了

**Comment by zn-coding** [comment]
> > 感谢回复，这个问题已经解决啦------------------ 原始邮件 ------------------ 发件人: "WYXinna"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年5月28日(星期四) 晚上11:21 收件人: "NetManAIOps/Bagel"<[Bagel@noreply.github.com](mailto:Bagel@noreply.github.com)>; 抄送: "zn-coding"<[mailfromzn@qq.com](mailto:mailfromzn@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [NetManAIOps/Bagel] ValueError: dataset attribute should not be set after KpiFrameDataLoader is initialized (#2)
> 
> 求助😭请问你是怎么解决的呀

换个版本

**Comment by WYXinna** [comment]
> 哈哈哈，笑出了声，确实是pytorch版本的问题，换了一个就好了

好哒 谢谢

**Comment by heyanyidui** [comment]
把那行注释掉就好了，原因解释一下：

```python
class KpiFrameDataLoader(DataLoader):
    def __init__(self, dataset: Dataset, batch_size, shuffle=False, drop_last=False):
        super().__init__(dataset, batch_size=batch_size, shuffle=shuffle, drop_last=drop_last)
        # self.dataset = dataset
        self.shuffle = shuffle
        self.index_sampler = None  # type: _IndexSampler
```
因为父类的 init 已经加载过 dataset 了
