### ISSUE TITLE
名字

### ISSUE THREAD

**Issue by zzj0402** [lizeyan/Bagel#6]
老铁，我觉得你的detect好像得叫predict啊

**Comment by lizeyan** [comment]
代码里的predict指的是获取reconstruction probability（因为这一步相当于在predict对应的正常值），detect指的是获取每个点是正常还是异常的判断结果。

**Comment by zzj0402** [comment]
二分类Predict应该是0或1。 一个同事找了半天。 我觉得最后加个softmax也可以。阈值感觉有点僵硬。
