### ISSUE TITLE
requirement.txt

### ISSUE THREAD

**Issue by tellyoung** [lizeyan/Bagel#7]
版本冲突 py37下mltoolkit 版本错误

**Comment by tellyoung** [comment]
python3.7 现在并没有对应的 torch==0.4

**Comment by lizeyan** [comment]
mltoolkit最新版可能不行。你找个和这个代码时间差不多的mltoolkit的commit试试？我本地也没有这个环境了，所以我也查不到我具体用的是哪个版本的mltoollkit。
torch版本的问题就不太清楚了，以前是可以的。你可以找找torch 0.4的whl包来手动安装，可能只是不开放用pypi直接装了？

**Comment by tellyoung** [comment]
嗯嗯 现在pypi安装不支持torch0.4.*了
