### ISSUE TITLE
what is the meaning of the parameter of the function “label_sampling”? And the question on how to find a threshold

### ISSUE THREAD

**Issue by jjd1123** [lizeyan/Bagel#8]
Hello, I have met some problems during my training, that is as long as I changed the parameters of **train_kpi.label_sampling(0.)** and **test_kpi.label_sampling(0.)** to **(1.)**, the best F1- score became very low, which is less than 0.1. So I would appreciate it if you could tell me why the program samples some labels before traning and how will it affect the algorithm if I change the sampling ratio. Thank you!

**Comment by lizeyan** [comment]
The dataset contains labels and our code loads them by default. However, our algorithm is unsupervised, so we should remove the labels by `label_sampling`.

**Comment by jjd1123** [comment]
Hello, thank you very much for your answer. By the way, I think there exist some problems with the function `threshold_ml`. It needs labels to find the best threshold that corresponds to the best F1-score. However, there doesn't exist any label in real situation. So should I write a function by myself to find anomalies by clustering algorithm based on the reconstructed error? Or can I use the `detect` function in class `dountx` without labels? Thank you!

**Comment by lizeyan** [comment]
Yes，the best F1-score is only used to show the best performance of our algorithm and is not practical. In practice, we need to tune the threshold manually. Of course, you can design some threshold selection algorithm. We have explored this direction. But I think, in the end, we need manual threshold tuning to maximize the performance and make the anomaly detection meet the customized requirements.Zeyan LI 李则言E-Mail: ***@***.*** studentDepartment of Computer ScienceTsinghua UniversityBeijing, China在 2022年8月12日，10:59，jidong Jia ***@***.***> 写道：﻿
Hello, thank you very much for your answer. By the way, I think there exist some problems with the function threshold_ml. It needs labels to find the best threshold that corresponds to the best F1-score. However, there doesn't exist any label in real situation. So should I write a function by myself to find anomalies by clustering algorithm based on the reconstructed error? Or can I use the detect function in class dountx without labels? Thank you!

**Comment by jjd1123** [comment]
Thanks a lot! Wish you have a nice day!
